# Generated by Django 4.2.2 on 2024-04-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
