# Generated by Django 4.2.2 on 2024-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_forumtopic_forumpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
