# Generated by Django 4.2.2 on 2024-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Жанр')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'Сообщение на форуме', 'verbose_name_plural': 'Сообщения на форуме'},
        ),
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'verbose_name': 'Топик на форуме', 'verbose_name_plural': 'Топики на форуме'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'Запрос на покупку', 'verbose_name_plural': 'Запросы на покупку'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='shop_app.genre', verbose_name='Жанры'),
        ),
    ]
