# Generated by Django 4.2.2 on 2024-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0024_remove_book_genre_delete_genre_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=256, verbose_name='Жанр'),
        ),
    ]
