# Generated by Django 4.2.2 on 2024-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0030_genre_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
