# Generated by Django 4.2.2 on 2024-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0031_purchaserequest_payment_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('P', 'Ожидает подтверждения'), ('C', 'Подтверждено'), ('X', 'Отменено')], default='P', max_length=1),
        ),
    ]
