# Generated by Django 4.2.2 on 2024-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0032_remove_purchaserequest_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
