# Generated by Django 4.2.2 on 2024-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0033_remove_purchaserequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
