# Generated by Django 4.2.2 on 2024-05-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0034_purchaserequest_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='rejected',
        ),
    ]
