# Generated by Django 4.2.2 on 2024-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0035_remove_purchaserequest_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='book',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='books',
            field=models.ManyToManyField(to='shop_app.book'),
        ),
    ]
